<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5966DD6" failures="1" tests="1" name="AddCustomerTest" time="0.022" errors="0" timestamp="2024-02-27T18:56:37 IST">
  <testcase classname="testCases.AddCustomerTest" name="addCustomer" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at testCases.AddCustomerTest.getData(AddCustomerTest.java:53)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <testcase classname="base.TestBase" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="base.TestBase" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
</testsuite> <!-- AddCustomerTest -->
